# Run this workflow whenever dim.json has keys updated and you have updated the keys in the other i18n files as well
# Does not notify #i18n in discord
name: i18n upload all (manual only)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DIM
        uses: actions/checkout@v2

      - name: Sort dim.json
        run: dimJSON="$(jq -S . src/locale/dim.json)" && echo "${dimJSON}" > src/locale/dim.json

      - name: sort locale dim.json
        run: |
          allLocales=("de" "es" "es-mx" "fr" "it" "ja" "ko" "pl" "pt-br" "ru" "zh-chs" "zh-cht")
          for lang in ${allLocales[@]}; do
            jq -S . src/locale/$lang/dim.json > src/locale/$lang/dim_sorted.json && mv src/locale/$lang/dim_sorted.json src/locale/$lang/dim.json
          done

      - name: Upload updated dim.json to crowdin
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: true
          upload_translations: true
          source: src/locale/dim.json
          translation: src/locale/%android_code%/dim.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
